name: filebrowser

services:
  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser:s6

    labels:
      homepage.description: "Browse Files from Web UI"
      homepage.group: "Media"
      homepage.href: "https://filebrowser.lab.drake.cloud"
      homepage.icon: "filebrowser.svg"
      homepage.name: "Filebrowser"
      homepage.weight: "1"

    ports:
      - "8092:80/tcp"

    volumes:
      - $CONTAINER_APPS_DIR/filebrowser/database/filebrowser.db:/database/filebrowser.db
      - $CONTAINER_APPS_DIR/filebrowser/settings/settings.json:/config/settings.json
      - $MEDIA_DIR:/srv

    logging:
      driver: ${LOG_DRIVER}
      options:
        splunk-url: ${LOG_SPLUNK_URL}
        splunk-token: ${LOG_SPLUNK_TOKEN}
        splunk-format: ${LOG_SPLUNK_FORMAT}
        splunk-verify-connection: ${LOG_SPLUNK_VERIFY_CONNECTION}
        splunk-source: sonarr
        tag: ${LOG_TAG}

    environment:
      TZ: ${TZ}
      PGID: ${PGID}
      PUID: ${PUID}

    restart: unless-stopped
