version: "3"
name: nextcloud

services:
  nextcloud:
    container_name: nextcloud
    image:  nextcloud:latest

    labels:
      homepage.description: "Document Storage"
      homepage.group: "Media"
      homepage.href: "https://nextcloud.lab.drake.cloud"
      homepage.icon: "nextcloud.svg"
      homepage.name: "Nextcloud"
      homepage.weight: "1"

    ports:
      - "8086:80/tcp"

    volumes:
      - $MEDIA_DIR/media/nextcloud:/media
      - $CONTAINER_APPS_DIR/nextcloud:/var/www/html

    environment:
      TZ: ${TZ}
      PGID: ${PGID}
      PUID: ${PUID}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}

    links:
      - nextcloud-db

    restart: unless-stopped

  nextcloud-db:
    image: mariadb:10.6
    container_name: nextcloud-db

    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW

    volumes:
      - $CONTAINER_APPS_DIR/nextcloud-db:/var/lib/mysql

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}

    restart: unless-stopped
