version: "3"
name: fleetdm

services:
  fleetdm:
    container_name: fleetdm
    image: fleetdm/fleet:latest

    labels:
      homepage.description: "Osquery - Fleet"
      homepage.group: "Infrastructure"
      homepage.href: "https://fleet.lab.drake.cloud"
      homepage.icon: "https://fleetdm.com/images/press-kit/fleet-logo-white.svg"
      homepage.name: "Fleet - Osquery"

    ports:
      - "8091:8080/tcp"

    command: sh -c "/usr/bin/fleet prepare db --no-prompt && /usr/bin/fleet serve"

    volumes:
      - $CONTAINER_APPS_DIR/fleetdm/fleet:/fleet
      - $CONTAINER_APPS_DIR/fleetdm/fleet/logs:/logs
      - $CONTAINER_APPS_DIR/fleetdm/fleet/vulndb:/vulndb

    environment:
      TZ: ${TZ}
      FLEET_MYSQL_ADDRESS: ${FLEET_MYSQL_ADDRESS}
      FLEET_MYSQL_DATABASE: ${FLEET_MYSQL_DATABASE}
      FLEET_MYSQL_USERNAME: ${FLEET_MYSQL_USERNAME}
      FLEET_MYSQL_PASSWORD: ${FLEET_MYSQL_PASSWORD}
      FLEET_REDIS_ADDRESS: ${FLEET_REDIS_ADDRESS}
      FLEET_LOGGING_JSON: "true"
      FLEET_OSQUERY_STATUS_LOG_PLUGIN: "filesystem"
      FLEET_FILESYSTEM_STATUS_LOG_FILE: "/logs/osqueryd.status.log"
      FLEET_OSQUERY_RESULT_LOG_PLUGIN: "filesystem"
      FLEET_FILESYSTEM_RESULT_LOG_FILE: "/logs/osqueryd.results.log"
      FLEET_VULNERABILITIES_CURRENT_INSTANCE_CHECKS: "yes"
      FLEET_VULNERABILITIES_DATABASES_PATH: "/vulndb"
      FLEET_VULNERABILITIES_PERIODICITY: "10m"
      FLEET_SERVER_TLS: "false"

    depends_on:
      - fleet-mysql
      - fleet-redis

    logging:
      driver: ${LOG_DRIVER}
      options:
        splunk-url: ${LOG_SPLUNK_URL}
        splunk-token: ${LOG_SPLUNK_TOKEN}
        splunk-format: ${LOG_SPLUNK_FORMAT}
        splunk-verify-connection: ${LOG_SPLUNK_VERIFY_CONNECTION}
        splunk-source: fleetdm
        tag: ${LOG_TAG}

    restart: unless-stopped
    
  fleet-redis:
    container_name: fleet-redis
    image: redis:latest

    expose:
      - 6379

    depends_on:
      - fleet-mysql

    restart: unless-stopped
      
    logging:
      driver: ${LOG_DRIVER}
      options:
        splunk-url: ${LOG_SPLUNK_URL}
        splunk-token: ${LOG_SPLUNK_TOKEN}
        splunk-format: ${LOG_SPLUNK_FORMAT}
        splunk-verify-connection: ${LOG_SPLUNK_VERIFY_CONNECTION}
        splunk-source: fleetdm-redis
        tag: ${LOG_TAG}
  
  fleet-mysql:
    container_name: fleet-mysql
    image: mysql:8.0

    expose:
      - 3306

    cap_add:
      - SYS_NICE

    volumes:
      - $CONTAINER_APPS_DIR/fleetdm/mysql/data:/var/lib/mysql

    environment:
      TZ: ${TZ}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${FLEET_MYSQL_DATABASE}
      MYSQL_USER: ${FLEET_MYSQL_USERNAME}
      MYSQL_PASSWORD: ${FLEET_MYSQL_PASSWORD}

    restart: unless-stopped

    logging:
      driver: ${LOG_DRIVER}
      options:
        splunk-url: ${LOG_SPLUNK_URL}
        splunk-token: ${LOG_SPLUNK_TOKEN}
        splunk-format: ${LOG_SPLUNK_FORMAT}
        splunk-verify-connection: ${LOG_SPLUNK_VERIFY_CONNECTION}
        splunk-source: fleetdm-mysql
        tag: ${LOG_TAG}
