version: "3"
name: netboot

services:
  netboot:
    container_name: netboot
    image: linuxserver/netbootxyz:latest

    labels:
      homepage.description: "PXE Boot"
      homepage.group: "Infrastructure"
      homepage.href: "https://pxe.lab.drake.cloud"
      homepage.icon: "netboot.png"
      homepage.name: "Netboot.xyz"

    ports:
      - "3000:3000/tcp"
      - "69:69/udp"
      - "8085:80/tcp"

    volumes:
      - $CONTAINER_APPS_DIR/netboot/assets:/assets
      - $CONTAINER_APPS_DIR/netboot/config:/config

    logging:
      driver: ${LOG_DRIVER}
      options:
        splunk-url: ${LOG_SPLUNK_URL}
        splunk-token: ${LOG_SPLUNK_TOKEN}
        splunk-format: ${LOG_SPLUNK_FORMAT}
        splunk-verify-connection: ${LOG_SPLUNK_VERIFY_CONNECTION}
        splunk-source: netboot
        tag: ${LOG_TAG}

    environment:
      TZ: ${TZ}
      PGID: ${PGID}
      PUID: ${PUID}

    restart: unless-stopped
