version: "3"
name: homepage

services:
  homepage:
    container_name: homepage
    image: ghcr.io/gethomepage/homepage:latest

    volumes:
      - $CONTAINER_APPS_DIR/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro

    ports:
      - "3001:3000/tcp"

    logging:
      driver: ${LOG_DRIVER}
      options:
        splunk-url: ${LOG_SPLUNK_URL}
        splunk-token: ${LOG_SPLUNK_TOKEN}
        splunk-format: ${LOG_SPLUNK_FORMAT}
        splunk-source: homepage
        tag: ${LOG_TAG}

    environment:
      TZ: ${TZ}

    restart: unless-stopped
