version: "3"
name: watchtower

services:
  watchtower:
    command:
      - "--cleanup"
      - "--include-restarting"
      - "--debug"
      - "--http-api-update"
      - "--http-api-metrics"
      - "--http-api-periodic-polls"

    container_name: "watchtower"

    environment:
      - TZ=${TZ}
      - WATCHTOWER_NOTIFICATIONS=${WATCHTOWER_NOTIFICATIONS}
      - WATCHTOWER_NOTIFICATION_URL=${WATCHTOWER_NOTIFICATION_URL}
      - WATCHTOWER_HTTP_API_TOKEN=${WATCHTOWER_HTTP_API_TOKEN}
      - WATCHTOWER_SCHEDULE=${WATCHTOWER_SCHEDULE}
      - WATCHTOWER_NOTIFICATIONS_HOSTNAME=${WATCHTOWER_NOTIFICATIONS_HOSTNAME}
      - WATCHTOWER_NO_STARTUP_MESSAGE={WATCHTOWER_NO_STARTUP_MESSAGE}

    image: "containrrr/watchtower:latest"

    labels:
      com.centurylinklabs.watchtower.enable: "true"
      homepage.description: "Docker Container Updater"
      homepage.group: "Infrastructure"
      homepage.icon: "watchtower.svg"
      homepage.name: "Watchtower"
      homepage.href: "https://watchtower.lab.drake.cloud"
      homepage.weight: "-4"
      homepage.widget.type: "watchtower"
      homepage.widget.url: "https://watchtower.lab.drake.cloud"
      homepage.widget.key: ${WATCHTOWER_HTTP_API_TOKEN}

    logging:
      driver: ${LOG_DRIVER}
      options:
        splunk-url: ${LOG_SPLUNK_URL}
        splunk-token: ${LOG_SPLUNK_TOKEN}
        splunk-format: ${LOG_SPLUNK_FORMAT}
        splunk-verify-connection: ${LOG_SPLUNK_VERIFY_CONNECTION}
        splunk-source: watchtower
        tag: ${LOG_TAG}
        
    network_mode: "bridge"

    ports:
      - '8083:8080'

    restart: "always"

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
