version: "3"
name: tooljet

services:
  tooljet:

    container_name: tooljet
    image: tooljet/tooljet:EE-LTS-latest

    labels:
      homepage.description: "Build Internal Apps"
      homepage.group: "Infrastructure"
      homepage.href: "https://tooljet.lab.drake.cloud"
      homepage.icon: "tooljet.svg"
      homepage.name: "Tooljet"

    ports:
      - 8093:80

    depends_on:
      - tooljet-db
      - tooljet-redis

    environment:
      TZ: ${TZ}
      PGID: ${PGID}
      PUID: ${PUID}
      SERVE_CLIENT: "true"
      PORT: "80"
      TOOLJET_HOST: ${TOOLJET_HOST}
      LOCKBOX_MASTER_KEY: ${TOOLJET_LOCKBOX_MASTER_KEY}
      SECRET_KEY_BASE: ${TOOLJET_SECRET_KEY_BASE}
      PGRST_JWT_SECRET: ${TOOLJET_PGRST_JWT_SECRET}
      PG_PASS: ${PG_PASS}
      TOOLJET_DB_PASS: ${TOOLJET_DB_PASS}
      PGRST_DB_URI: ${PGRST_DB_URI}

    logging:
      driver: ${LOG_DRIVER}
      options:
        splunk-url: ${LOG_SPLUNK_URL}
        splunk-token: ${LOG_SPLUNK_TOKEN}
        splunk-format: ${LOG_SPLUNK_FORMAT}
        splunk-verify-connection: ${LOG_SPLUNK_VERIFY_CONNECTION}
        splunk-source: tooljet
        tag: ${LOG_TAG}

    restart: always

    command: npm run start:prod
    tty: true
    stdin_open: true

  tooljet-db:
    container_name: tooljet-db
    image: postgres:13

    volumes:
      - $CONTAINER_APPS_DIR/tooljet-db:/var/lib/postgresql/data

    environment:
      TZ: ${TZ}
      PGID: ${PGID}
      PUID: ${PUID}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}

    logging:
      driver: ${LOG_DRIVER}
      options:
        splunk-url: ${LOG_SPLUNK_URL}
        splunk-token: ${LOG_SPLUNK_TOKEN}
        splunk-format: ${LOG_SPLUNK_FORMAT}
        splunk-verify-connection: ${LOG_SPLUNK_VERIFY_CONNECTION}
        splunk-source: tooljet-db
        tag: ${LOG_TAG}

    restart: always

  tooljet-db-rest:
    container_name: tooljet-db-rest
    image: postgrest/postgrest:v12.0.2

    depends_on:
      - tooljet-db

    environment:
      TZ: ${TZ}
      PGID: ${PGID}
      PUID: ${PUID}
      PGRST_HOST: ${PGRST_HOST}
      PGRST_DB_URI: ${PGRST_DB_URI}

    logging:
      driver: ${LOG_DRIVER}
      options:
        splunk-url: ${LOG_SPLUNK_URL}
        splunk-token: ${LOG_SPLUNK_TOKEN}
        splunk-format: ${LOG_SPLUNK_FORMAT}
        splunk-verify-connection: ${LOG_SPLUNK_VERIFY_CONNECTION}
        splunk-source: tooljet-db-rest
        tag: ${LOG_TAG}

    restart: always

  tooljet-redis:
    container_name: tooljet-redis
    image: redis:6.2

    environment:
      TZ: ${TZ}
      PGID: ${PGID}
      PUID: ${PUID}
      MASTER: ${REDIS_HOST}
      REDIS_USER: ${REDIS_USER}
      REDIS_PASSWORD: ${REDIS_PASSWORD}

    logging:
      driver: ${LOG_DRIVER}
      options:
        splunk-url: ${LOG_SPLUNK_URL}
        splunk-token: ${LOG_SPLUNK_TOKEN}
        splunk-format: ${LOG_SPLUNK_FORMAT}
        splunk-verify-connection: ${LOG_SPLUNK_VERIFY_CONNECTION}
        splunk-source: tooljet-redis
        tag: ${LOG_TAG}

    restart: always
