version: "3"
name: media-players

services:
  plex:
    container_name: plex
    image: linuxserver/plex:latest

    labels:
      homepage.description: "Media Player for Entertainment"
      homepage.group: "Media"
      homepage.href: "https://plex.lab.drake.cloud"
      homepage.icon: "plex.png"
      homepage.name: "Plex"
      homepage.weight: "-100"
      homepage.widget.key: ${PLEX_API_KEY}
      homepage.widget.type: "plex"
      homepage.widget.url: "https://plex.lab.drake.cloud"

    volumes:
      - $CONTAINER_APPS_DIR/plex/transcode:/transcode
      - $CONTAINER_APPS_DIR/plex:/config
      - $MEDIA_DIR/media:/data

    devices:
      - "/dev/dri:/dev/dri"

    network_mode: "host"

    environment:
      TZ: ${TZ}
      PGID: ${PGID}
      PUID: ${PUID}
      PLEX_GID: ${PLEX_GID}
      PLEX_UID: ${PLEX_UID}
      hostname: ${PLEX_HOSTNAME}
      ALLOWED_NETWORKS: ${PLEX_ALLOWED_NETWORKS}
      VERSION: ${PLEX_VERSION}

    logging:
      driver: ${LOG_DRIVER}
      options:
        splunk-url: ${LOG_SPLUNK_URL}
        splunk-token: ${LOG_SPLUNK_TOKEN}
        splunk-format: ${LOG_SPLUNK_FORMAT}
        splunk-verify-connection: ${LOG_SPLUNK_VERIFY_CONNECTION}
        splunk-source: plex
        tag: ${LOG_TAG}

    restart: always

  tautulli:
    container_name: tautulli
    image: linuxserver/tautulli:latest

    labels:
      homepage.description: "Plex Stats"
      homepage.group: "Media"
      homepage.href: "https://plexstats.lab.drake.cloud"
      homepage.icon: "tautulli.svg"
      homepage.name: "Tautulli"

    ports:
      - "8182:8181/tcp"

    volumes:
      - $CONTAINER_APPS_DIR/plex/Library/Application Support/Plex Media Server/Logs:/logs
      - $CONTAINER_APPS_DIR/tautulli:/config

    logging:
      driver: ${LOG_DRIVER}
      options:
        splunk-url: ${LOG_SPLUNK_URL}
        splunk-token: ${LOG_SPLUNK_TOKEN}
        splunk-format: ${LOG_SPLUNK_FORMAT}
        splunk-verify-connection: ${LOG_SPLUNK_VERIFY_CONNECTION}
        splunk-source: tautulli
        tag: ${LOG_TAG}

    environment:
      TZ: ${TZ}
      PGID: ${PGID}
      PUID: ${PUID}

    restart: unless-stopped
