version: "3"
name: cribl

services:
  cribl:
    container_name: cribl
    image: cribl/cribl:latest

    labels:
      homepage.description: "Log Enrichment / Transformation"
      homepage.group: "Infrastructure"
      homepage.href: "https://cribl.lab.drake.cloud"
      homepage.icon: "mdi-arrow-right-drop-circle-outline"
      homepage.name: "Cribl"

    ports:
      - "9000:9000/tcp"
      - "8088:8088/tcp"

    volumes:
      - $CONTAINER_APPS_DIR/cribl:${CRIBL_VOLUME_DIR}

    logging:
      driver: ${LOG_DRIVER}
      options:
        splunk-url: ${LOG_SPLUNK_URL}
        splunk-token: ${LOG_SPLUNK_TOKEN}
        splunk-format: ${LOG_SPLUNK_FORMAT}
        splunk-verify-connection: ${LOG_SPLUNK_VERIFY_CONNECTION}
        splunk-source: cribl
        tag: ${LOG_TAG}
        
    environment:
      TZ: ${TZ}
      PGID: ${PGID}
      PUID: ${PUID}
      CRIBL_VOLUME_DIR: ${CRIBL_VOLUME_DIR}

    restart: unless-stopped
